services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SENDGRID_USERNAME: ${EMAIL_SERVICE_API_KEY}
      SENDGRID_PASSWORD: ${EMAIL_SERVICE_FROM_EMAIL}
    depends_on:
      - mysql
      - rabbitmq

volumes:
  mysql-data:
